In [1]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [2]:
fake = Faker()
random.seed(42)

In [4]:
# Genrateing 200 client details useing Faker and Random
clients = []

for _ in range(200):
    client ={
        "Client_ID" : fake.uuid4(),
         "Name" : fake.name(),
        "Nationality" : fake.country(),
        "Documented_submitted" : random.choice([True, False]),
        "AML_Flag" : random.choices([True, False], weights=[0.1, 0.9])[0],  
        "KYC_Verified": random.choice([True, False]),
    }
    clients.append(client)

df = pd.DataFrame(clients)
df.head()

,Client_ID,Name,Nationality,Documented_submitted,AML_Flag,KYC_Verified
0,3ff5dcb5-f5bb-4d9b-88ac-dc9188a13f60,Vincent Bradford,Suriname,False,False,True
1,157a3910-194c-4983-ad94-73d7aaa38f0b,Mary Lewis,Samoa,False,False,False
2,5db511fb-7004-40e4-9ba5-c3eac2fefc8b,Tonya Smith,Saint Martin,False,False,True
3,eb4fef40-0f54-4e27-8562-f070ff4cb711,Vanessa Miller,Sweden,False,False,True
4,de1f9f4b-b879-4236-a9e6-feee0710cc13,Robert Thornton,Nicaragua,False,False,False

In [10]:
# Review Logic (Approval / Rejection / Escalation)
def review_client(row):
    if not row['Documented_submitted']:
        return "Rejected- Missing Docs"
    if row['AML_Flag']:
        return "Escalated - AML Alert"
    if not row['KYC_Verified']:
        return "Rejected - KYC Failed"
    else:
        return "approved"

# Applying logic to dataset useing added column Review_Status
df["Review_Status"] = df.apply(review_client, axis=1)

In [11]:
df.head()

,Client_ID,Name,Nationality,Documented_submitted,AML_Flag,KYC_Verified,Review_Status
0,3ff5dcb5-f5bb-4d9b-88ac-dc9188a13f60,Vincent Bradford,Suriname,False,False,True,Rejected- Missing Docs
1,157a3910-194c-4983-ad94-73d7aaa38f0b,Mary Lewis,Samoa,False,False,False,Rejected- Missing Docs
2,5db511fb-7004-40e4-9ba5-c3eac2fefc8b,Tonya Smith,Saint Martin,False,False,True,Rejected- Missing Docs
3,eb4fef40-0f54-4e27-8562-f070ff4cb711,Vanessa Miller,Sweden,False,False,True,Rejected- Missing Docs
4,de1f9f4b-b879-4236-a9e6-feee0710cc13,Robert Thornton,Nicaragua,False,False,False,Rejected- Missing Docs

In [12]:
print(df["Review_Status"].value_counts())

Review_Status
Rejected- Missing Docs    115
Rejected - KYC Failed      39
approved                   37
Escalated - AML Alert       9
Name: count, dtype: int64

In [13]:
# Exporting data as csv
 df.to_csv("client_data.csv", index=False)